spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      uri: mongodb://user:secret@mongo1.example.com:12345,mongo2.example.com:23456/test
#      uri: mongodb://admin:password@ds235180.mlab.com:35180/heroku_wm2c114x
      uri: ${MONGODB_URI}
      grid-fs-database: images
logging:
  level:
    com.example: DEBUG
    org.springframework.web: DEBUG